//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDMonHoc
{
    using System;
    using System.Collections.Generic;
    
    public partial class Monhoc
    {
        public Monhoc()
        {
        }

        public Monhoc(string iDMH, string mA_HK, string tenMH, int soTC, int lyThuyet, int thucHanh)
        {
            IDMH = iDMH;
            MA_HK = mA_HK;
            TenMH = tenMH;
            SoTC = soTC;
            LyThuyet = lyThuyet;
            ThucHanh = thucHanh;
        }

        public string IDMH { get; set; }
        public string MA_HK { get; set; }
        public string TenMH { get; set; }
        public int SoTC { get; set; }
        public int LyThuyet { get; set; }
        public int ThucHanh { get; set; }
    }
}
