//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomTriTin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemSV
    {
        public string MSSV { get; set; }
        public string IDMH { get; set; }
        public string MaGV { get; set; }
        public string Ma_HK { get; set; }
        public Nullable<double> DiemLan1 { get; set; }
        public Nullable<double> DiemLan2 { get; set; }
        public Nullable<double> DiemTichLuy { get; set; }
        public string DiemChu { get; set; }
    }
}
