//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhomTriTin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public string MaGV { get; set; }
        public string TenGV { get; set; }
        public Nullable<int> GioiTinhGV { get; set; }
        public Nullable<System.DateTime> NamSinhGV { get; set; }
        public string TrinhDoGV { get; set; }
        public string EmailGV { get; set; }
        public string SDT { get; set; }
    }
}
