//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PE_CE140469_LeDucHoa
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string IDCustomer { get; set; }
        public string IDStaff { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
